package com.periculum.internal.models

import com.periculum.models.ErrorType

/*internal data class AnalyticsResponseModel(
    val key: Int,
    val name: String?,
    val clientBvn: String?,
    val clientNin: String?,
    val clientFullName: String?,
    val accountType: String?,
    val accountName: String?,
    val bankName: String?,
    val startDate: String?,
    val endDate: String?,
    val createdDate: String?,
    val spendAnalysis: SpendAnalysisModel?,
    val transactionPatternAnalysis: TransactionPatternAnalysisModel?,
    val behavioralAnalysis: BehavioralAnalysisModel?,
    val cashFlowAnalysis: CashFlowAnalysisModel,
    val incomeAnalysis : IncomeAnalysisModel?
)*/

internal data class AnalyticsResponseModel(val responseBody: String = "", val isError: Boolean, val errorType: ErrorType = ErrorType.Null)

internal data class SpendAnalysisModel(
    val averageMonthlySpendOnTransfer: Double?,
    val averageMonthlySpendOnAtmAndPOS: Double?,
    val averageMonthlySpendOnUSSD: Double?,
    val averageMonthlySpendOnGamblingval : Double?,
    val averageMonthlySpendOnAirtimeAndData: Double?,
    val averageMonthlySpendOnUtilities: Double?,
    val averageMonthlySpendOnOnlineAndWeb: Double?,
    val averageMonthlySpendOnTransportation: Double?,
    val averageMonthlySpendOnHealth: Double?,
    val averageMonthlySpendOnTravel: Double?,
    val averageMonthlySpendOnEntertainment: Double?,
    val averageMonthlySpendOnHospitalityAndFood: Double?,
    val averageMonthlySpendOnRent: Double?,
    val averageMonthlySpendOnInsurance: Double?,
    val averageMonthlySpendOnChargesAndStampDuty: Double?,
    val averageMonthlySpendOnInternationalTransactions: Double?,
    val averageMonthlyTotalExpenses: Double?,
    val averageMonthlyRecurringExpense: Double?,
    val totalSpendOnTransfer: Double?,
    val totalSpendOnAtmAndPOS: Double?,
    val totalSpendOnUSSD: Double?,
    val totalSpendOnGambling: Double?,
    val totalSpendOnAirtimeAndData: Double?,
    val totalSpendOnUtilities: Double?,
    val totalSpendOnOnlineAndWeb: Double?,
    val totalSpendOnTransportation: Double?,
    val totalSpendOnHealth: Double?,
    val totalSpendOnEntertainment: Double?,
    val totalSpendOnHospitalityAndFood: Double?,
    val totalSpendOnRent: Double?,
    val totalSpendOnInsurance: Double?,
    val totalSpendOnChargesAndStampDuty: Double?,
    val totalSpendOnInternationalTransactions: Double?,
    val totalMonthlyExpenses: Double?,
)

internal data class TransactionPatternAnalysisModel(
    val lastDayOfCredit: String?,
    val lastDayOfDebit: String?,
    val percentDebitTransactions: Double?,
    val totalNumberOfTransactions: Double?,
    val percentOfTransactionsLessThan10ThousandNaira: Double?,
    val percentOfTransactionsBetween10ThousandTo100ThousandNaira: Double?,
    val percentOfTransactionsBetween100ThousandTo500ThousandNaira: Double?,
    val percentOfTransactionsBetween500ThousandToOneMillionNaira: Double?,
    val percentOfTransactionsGreaterThanOneMillionNaira: Double?,
    val percentNumberOfDaysTransactionsWasLessThan10ThousandNaira: Double?,
    val percentOfBalancesLessThan10ThousandNaira: Double?,
    val percentOfBalancesBetween10ThousandTo100ThousandNaira: Double?,
    val percentOfBalancesBetween100ThousandTo500ThousandNaira: Double?,
    val percentOfBalancesBetween500ThousandToOneMillionNaira: Double?,
    val percentOfBalancesGreaterThanOneMillionNaira: Double?,
    val percentNumberOfDaysBalanceWasLessThan10ThousandNaira: Double?,
    val mostFrequentBalanceRange: String?,
    val mostFrequentTransactionRange: String?,
    val numberOfCardRequests: Double?,
    val percentCreditTransactions: Double?,
)

internal data class BehavioralAnalysisModel(
    val monthToMonthInflowToOutflowRate: String?,
    val overallInflowToOutflowRate: String?,
    val totalLoanAmount: Double?,
    val totalLoanRepaymentAmount: Double?,
    val loanInflowRate: Double?,
    val loanRepaymentToInflowRate: Double?,
    val numberOfCreditLoanTransactions: Double?,
    val numberOfDebitRepaymentTransactions: Double?,
    val gamblingStatus: String?,
    val gamblingRate: Double?,
    val accountActivity: Double?,
    val percentOfInflowIrregularity: Double?,
    val averageMonthlyLoanAmount: Double?,
    val averageMonthlyLoanRepaymentAmount: Double?,
)

internal data class CashFlowAnalysisModel(
    val totalCreditTurnover: Double?,
    val totalDebitTurnOver: Double?,
    val averageMonthlyCredits: Double?,
    val averageMonthlyDebits: Double?,
    val averageWeeklyCredits: Double?,
    val averageWeeklyDebits: Double?,
    val averageMonthlyBalance: Double?,
    val averageWeeklyBalance: Double?,
    val numberOfTransactingMonths: Double?,
    val periodInStatement: String?,
    val yearInStatement: String?,
    val firstDateInStatement: String?,
    val lastDateInStatement: String?,
    val closingBalance: Double?,
)

internal data class IncomeAnalysisModel(
    val averagePredictedSalary: Double?,
    val isSalaryEarner: String?,
    val expectedSalaryPaymentDay: String?,
    val frequencyOfSalaryPayments: String?,
    val lastDateOfSalaryPayment: String?,
    val numberOfSalaryPayments: Double?,
    val hasOtherIncome: String?,
    val averageOtherIncome: Double?,
    val numberOfOtherIncomePayments: Double?,
    val netAverageMonthlyEarning: Double?,
)
